version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "4300:8000"
    depends_on:
      - db
  bot:
    build:
      context: tg_bot
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wecan
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
